server:
   port: 8080
   
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

