server:
   port: 8083
   
spring:
  cloud:
    stream:
      bindings:
        inboundAccountChanges:
          destination: accountChangeTopic
          content-type: application/json
        binder:
          zkNodes: localhost
          brokers: localhost
  zipkin:
    baseUrl:  http://localhost:9411

security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8080/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO
