server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  accountChangeTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost
  zipkin:
    baseUrl:  http://localhost:9411

security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8080/user
      
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        