
server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: classpath:config/,classpath:config/orderservice,classpath:config/productservice,classpath:config/accountservice
           encrypt:
              enable: false
            
#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin

encrypt: 
    key: configsymmetrickey
    
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO